-- ============================================================
-- XYFRONIX '26 AI PROMPT BATTLE - SUPABASE DATABASE
-- Run this entire file in Supabase SQL Editor.
-- The backend uses the SERVICE ROLE key; never expose it in frontend.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.quiz_settings (
  id integer primary key default 1,
  active_stage text check (active_stage in ('A','B')),
  status text not null default 'waiting' check (status in ('waiting','running','finished')),
  started_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.quiz_settings (id,status)
values (1,'waiting')
on conflict (id) do nothing;

create table if not exists public.participants (
  id uuid primary key,
  team_name text not null,
  college_name text not null,
  status text not null default 'waiting' check (status in ('waiting','live','submitted')),
  stage_a_score integer not null default 0,
  stage_a_correct integer not null default 0,
  stage_a_used integer not null default 0,
  stage_b_score integer not null default 0,
  stage_b_correct integer not null default 0,
  stage_b_used integer not null default 0,
  joined_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.participants(id) on delete cascade,
  stage text not null check (stage in ('A','B')),
  question_index integer not null,
  selected_option integer not null,
  is_correct boolean not null,
  marks integer not null default 0,
  submitted_at timestamptz not null default now(),
  unique(participant_id,stage,question_index)
);

create index if not exists idx_answers_participant on public.answers(participant_id);
create index if not exists idx_participants_status on public.participants(status);

alter table public.quiz_settings enable row level security;
alter table public.participants enable row level security;
alter table public.answers enable row level security;

-- Backend uses service_role, so it bypasses RLS.
-- These policies are intentionally restrictive for direct browser access.
-- No public anonymous write access is required by this architecture.

drop policy if exists "public_read_quiz_settings" on public.quiz_settings;
drop policy if exists "public_read_participants" on public.participants;
drop policy if exists "public_read_answers" on public.answers;

create policy "public_read_quiz_settings"
on public.quiz_settings for select
to anon, authenticated
using (true);

create policy "public_read_participants"
on public.participants for select
to anon, authenticated
using (true);

-- Do not allow anon users to read answer rows.
-- Answers are returned only through the backend after grading.

do $$
begin
  alter publication supabase_realtime add table public.quiz_settings;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.participants;
exception when duplicate_object then null;
end $$;
